config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers =>{:registrations => 'accesos'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :admin
	resources :bitacoras do
    get 'listar', :on => :collection
  end
	resources :tutoriales
  resources :casas
	resources :calles
	resources :numeros_casas
	resources :sentinela_usuarios
	resources :visitas_registro
	resources :fraccionamientos
  root :to => 'welcome#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calle.rb
class Calle < ApplicationRecord
end

app/models/casa.rb
class Casa < ApplicationRecord
end

app/models/fraccionamiento.rb
class Fraccionamiento < ApplicationRecord

end

##@fracc = Fraccionamiento.where("nombre LIKE ?", "%#{params[:buscador]}%")

app/models/numeros_casa.rb
class NumerosCasa < ApplicationRecord
end

app/models/sentinela_usuario.rb
class SentinelaUsuario < ApplicationRecord
end

app/models/user.rb
#class User < ApplicationRecord
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(conditions={})
    find_by(celular: conditions[:email]) || find_by(email: conditions[:email])
  end
end

class User < ActiveRecord::Base
  # you can also explicitly define enum as:  enum access_level: [:employee => 0, :company_admin => 1, :super_admin => 2}
  enum rol: [:residente, :vigilante, :admin, :super_admin]

end

app/models/visitas_registro.rb
class VisitasRegistro < ApplicationRecord
end

app/controllers/accesos_controller.rb
class AccesosController < Devise::RegistrationsController

  def create
    build_resource(registration_params)

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        respond_with resource, :location => after_sign_up_path_for(resource)
      end
    else
      clean_up_passwords
      respond_with resource
    end
  end

  private

  def registration_params
    params.require(:user).permit(:email, :nombre, :apellidos, :celular,
                                 :usuario, :password)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
	def index
		@fracc = Fraccionamiento.all #variable para pedir listado de fraccionamientos
	end
	def show
		@user = User.find(params[:id])
	end
end

app/controllers/calles_controller.rb
class CallesController < ApplicationController
  def index
  end
end

app/controllers/casas_controller.rb
class CasasController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def create
  end

  def new
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitacoras_helper.rb
module BitacorasHelper
end

app/helpers/calles_helper.rb
module CallesHelper
end

app/helpers/casas_helper.rb
module CasasHelper
end

app/helpers/numeros_casas_helper.rb
module NumerosCasasHelper
end

app/helpers/tutoriales_helper.rb
module TutorialesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<%= render 'layouts/header_normal' %>

<div class="row"></div>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <div class="content-wrapper" style="min-height: 100%">

        <section class="content">
          <table class="table table-bordered menu-principal">
            <tbody>
            <tr>
              <td> <%= link_to "USUARIOS", :controller => "sentinela_usuarios",:action => "index"  %></td>
              <td> <%= link_to "FRACCIONAMIENTOS", fraccionamientos_path%></td>
            </tr>
            <tr>

            </tbody>
          </table>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footbar.html.erb
<div id="w1" class="navbar-default navbar-fixed-bottom navbar" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SENTINELA", '/', class: "navbar-brand" %>
    </div>
      <!--<ul class="navbar-nav navbar-right nav">-->
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav navbar-right nav">
        <li>
          <%= link_to image_tag('iconos/app-store.png'),'https://www.apple.com/itunes/download/', class: 'footer-icon' %>
        </li>
        <li>
          <%= link_to image_tag('iconos/play-store.png'),'https://play.google.com/store/apps?hl=es', class: 'footer-icon' %>
        </li>
        <li>
          <%= link_to "FORMATO DE PAGO",'#' %>
        </li>
        <li>
          <%= link_to "TUTORIAL", tutoriales_path %>
        </li>
        <li>
          <%= link_to "CONTACTO",'#' %>
        </li>
        <li>
          <%= link_to "AVISO DE PRIVACIDAD",'#' %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_header_admin.html.erb
<div class="header-container">
	<!--<img src="<%= asset_path('sentinela/LogoSentinela.png') %>" />-->

<%= link_to image_tag('sentinela/LogoSentinela.png'), root_path %>
	<div class="header-user-container" >
		<div>Usuario :</div>
		<div><%= current_user.celular %></div>
    <div><%= current_user.nombre %> <%= current_user.apellidos %></div>

	<ul>
		<% if user_signed_in? %>
		<li>
			<%= link_to "cerrar session", destroy_user_session_path, method: :delete %>
		</li>
		<% else %>
		<li>
			<%= link_to "iniciar sesion", new_user_session_path %>
		</li>

		<% end %>
	</ul>

	</div>

	<img src="<%= asset_path('sentinela/administration.png') %>" />
</div>

app/views/layouts/_header_bitacora.html.erb
<div class="header-container">
	<!--<img src="<%= asset_path('sentinela/LogoSentinela.png') %>" />-->


<%= link_to image_tag('sentinela/LogoSentinela.png'), root_path %>
	<div class="header-user-container" >
		<div>Usuario :</div>
		<div><%= current_user.email %></div>
	
	<ul>
		<% if user_signed_in? %>
		<li>
			<%= link_to "cerrar session", destroy_user_session_path, method: :delete %>
		</li>
		<% else %>
		<li>
			<%= link_to "iniciar sesion", new_user_session_path %>
		</li>
	
		<% end %>
	</ul>

	</div>


	<img src="<%= asset_path('sentinela/bitacora.png') %>" />
</div>

app/views/layouts/_header_normal.html.erb
<header class="main-header">
  <a href="/" class="logo">
    Sentinela WEB
  </a>
  <nav class="navbar navbar-static-top" role="navigation">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Mostrar / Ocultar</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
            <i class="fa fa-envelope">
            </i>
            <span class="label  label-success"><%= "-" %></span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">Tiene 4 mensajes</li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<aside class="main-sidebar">
  <section class="sidebar" style="height: auto;">
    <div class="user-panel">
      <div class="image">
        <%= image_tag 'sentinela/avatar.png', class:'img-circle' %>
      </div>
      <div class="info">

          <p class="welcome">
            <span>
              <i class="fa fa-key">Conectado como: </i>
            </span>
          </p>

        <div class="name tooltip-sidebar-logout">
          <div class="user-name">
            <%= current_user.celular %>
          </div>
          <div class="last-name">
            <%= current_user.nombre %> <%= current_user.apellidos %>
            <%= link_to "" , destroy_user_session_path, method: :delete, class: 'fa fa-sign-out'%>
          </div>
        </div>
      </div>
    </div>
    <ul class="sidebar-menu tree" data-widget="tree">
      <li class="header">    </li>


      <li class="treeview">
        <a href="#">
          <i class="fa fa-cogs"></i>
          <span>ADMINISTRACIÓN</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull"></i>
            </span>
        </a>
        <ul class="treeview-menu" style="display: none">
          <li><%= link_to "USUARIOS", :controller => "sentinela_usuarios",:action => "index"  %></td></li>
          <li><td> <%= link_to "FRACCIONAMIENTOS", fraccionamientos_path%></td></li>
        </ul>
      </li>


      <li class="treeview">
        <%=link_to "BITÁCORA", {:controller => 'bitacoras', :action => 'index'}%>
      </li>


      <li class="treeview">
        <%=link_to "REGISTRO DE VISITAS", {:controller => 'visitas_registro', :action => 'index'}%>
      </li>


      <li class="treeview">
        <%=link_to "SERVICIO A USUARIOS", {:controller => 'admin', :action => 'index'}%>
      </li>

    </ul>
  </section>
</aside>

app/views/layouts/_main.html.erb
<div class="row"></div>
<div class="row">
    <div class="col-lg-12">
      <div class="table-responsive">
        <div class="content-wrapper" style="min-height: 100%">

          <section class="content">
            <table class="table table-bordered menu-principal">
              <tbody>
              <tr>
                <td>
                  <%= link_to image_tag('sentinela/administration.png',  class:'img-table-menu'),{:controller => :admin, :action => :index} %>
                  <h3><%=link_to "ADMINISTRACION", {:controller => 'admin', :action => 'index'}%> </h3>
                </td>
                <td>
                  <%= link_to image_tag('sentinela/bitacora.png',class:'img-table-menu'), {:controller => :bitacoras, :action => :index} %>
                  <h3><%=link_to "BITACORA", {:controller => 'bitacoras', :action => 'index'}%></h3>
                </td>
                <td>
                  <%= link_to image_tag('sentinela/registro.png',class:'img-table-menu') , {:controller => :visitas_registro, :action => :index} %>
                  <h3><%=link_to "REGISTRO", {:controller => 'visitas_registro', :action => 'index'}%></h3>
                </td>
                <td>
                  <%= link_to image_tag('sentinela/servicioausuarios.png',class:'img-table-menu') , {:controller => :admin, :action => :index} %>
                  <h3><%=link_to "SERVICIO A USUARIOS", {:controller => 'admin', :action => 'index'}%></h3>
                </td>
              </tr>
              </tbody>
            </table>

          </section>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sentinela</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:500" rel="stylesheet">
  </head>

  <body class="skin-blue sidebar">
  <div class="wrapper" style="height: auto">
  </div>

      <%= yield %>

    <% #devise suggested next lines %>
<% if notice %>
  <!--<p class="alert alert-success"><%= notice %></p>-->
<% end %>
<% if alert %>
  <!--<p class="alert alert-danger"><%= alert %></p>-->
<% end %>
  </body>
</html>