config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers =>{:registrations => 'accesos'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :admin
	resources :bitacoras do
    get 'listar', :on => :collection
  end
	resources :tutoriales
  resources :casas
	resources :calles
	resources :numeros_casas
	resources :sentinela_usuarios
	resources :visitas_registro
	resources :fraccionamientos
  root :to => 'welcome#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calle.rb
class Calle < ApplicationRecord
end

app/models/casa.rb
class Casa < ApplicationRecord
end

app/models/fraccionamiento.rb
class Fraccionamiento < ApplicationRecord

end

##@fracc = Fraccionamiento.where("nombre LIKE ?", "%#{params[:buscador]}%")

app/models/numeros_casa.rb
class NumerosCasa < ApplicationRecord
end

app/models/sentinela_usuario.rb
class SentinelaUsuario < ApplicationRecord
end

app/models/user.rb
#class User < ApplicationRecord
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(conditions={})
    find_by(celular: conditions[:email]) || find_by(email: conditions[:email])
  end
end

class User < ActiveRecord::Base
  # you can also explicitly define enum as:  enum access_level: [:employee => 0, :company_admin => 1, :super_admin => 2}
  enum rol: [:residente, :vigilante, :admin, :super_admin]

end

app/models/visitas_registro.rb
class VisitasRegistro < ApplicationRecord
end

app/controllers/accesos_controller.rb
class AccesosController < Devise::RegistrationsController

  def create
    build_resource(registration_params)

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        respond_with resource, :location => after_sign_up_path_for(resource)
      end
    else
      clean_up_passwords
      respond_with resource
    end
  end

  private

  def registration_params
    params.require(:user).permit(:email, :nombre, :apellidos, :celular,
                                 :usuario, :password)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
	def index
		@fracc = Fraccionamiento.all #variable para pedir listado de fraccionamientos
	end
	def show
		@user = User.find(params[:id])
	end
end

app/controllers/calles_controller.rb
class CallesController < ApplicationController
  def index
  end
end

app/controllers/casas_controller.rb
class CasasController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def create
  end

  def new
  end
end

app/controllers/sentinela_usuarios_controller.rb
class SentinelaUsuariosController < ApplicationController
  before_action :authenticate_user!
	def index
		@fracc = Fraccionamiento.all
    if params[:buscador]
      @u_sent = SentinelaUsuario.where("nombre LIKE ? OR apellidos like ? ", "%#{params[:buscador]}%" ,"%#{params[:buscador]}%").paginate(:per_page => 5, :page => params[:page])
    else
      @u_sent = SentinelaUsuario.all.paginate(:per_page => 5, :page => params[:page])
    end
    params[:buscador] = nil
    @mensajeborrar = "Está seguro de querer eliminar el registro "
	end

	def show
		@u_sent = SentinelaUsuario.find(params[:id])
    fuser = @u_sent.fraccionamiento
    @f_user = Fraccionamiento.find(fuser)
    @fraccionamientos = Fraccionamiento.all
  end

  def new
    @u_sent = SentinelaUsuario.new
    @fraccionamientos = Fraccionamiento.all
  end
  def create
    @u_sent = SentinelaUsuario.new(usent_params)
    if @u_sent.save
      redirect_to @u_sent
    else
      render :new
    end
  end

  def update
    @u_sent = SentinelaUsuario.find(params[:id])
    if @u_sent.update(usent_params)
      redirect_to @u_sent
    else
      render :edit
    end
  end
  def edit
    @u_sent = SentinelaUsuario.find(params[:id])
    @fraccionamientos = Fraccionamiento.all
  end

  def destroy
    SentinelaUsuario.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to sentinela_usuarios_path
  end

  def usent_params
    params.require(:sentinela_usuario).permit(:usuario,:nombre,:apellidos,:password,:email,:celular,:fraccionamiento,:domicilio,:calle,:numero)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_user!
	def index
		
	end

	def admin

	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitacoras_helper.rb
module BitacorasHelper
end

app/helpers/calles_helper.rb
module CallesHelper
end

app/helpers/casas_helper.rb
module CasasHelper
end

app/helpers/numeros_casas_helper.rb
module NumerosCasasHelper
end

app/helpers/sentinela_usuario_helper.rb
module SentinelaUsuarioHelper
end

app/helpers/tutoriales_helper.rb
module TutorialesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/sentinela_usuarios/_form-show.html.erb
<%= render 'layouts/header_normal' %>

<div class="row"></div>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <div class="content-wrapper" style="min-height: 100%">

        <section class="content">
          <div class="table table-bordered menu-principal">
            <div class="content-div">
              <h2><%= action_name %> USUARIO</h2>
              <div>
                <%= form_for(@u_sent) do |u|  %>
                    <ul class="flex-form">
                     <li>
                       <%= u.label :usuario, "Usuario :" %>
                       <%= u.text_field :usuario ,:disabled => true %>
                     </li>
                     <li>
                       <%= u.label :nombre, "Nombre :" %>
                       <%= u.text_field :nombre ,:disabled => true %>
                     </li>
                     <li>
                       <%= u.label :apellidos, "Apellidos :" %>
                       <%= u.text_field :apellidos ,:disabled => true %></li>
                      <li>
                       <%= u.label :password ,"Contraseña :"%>
                       <%= u.text_field :password ,:disabled => true %>
                      </li>
                      <li>
                       <%= u.label :email, "Correo Electrónico :" %>
                       <%= u.text_field :email ,:disabled => true %>
                      </li>
                      <li>
                       <%= u.label :celular, "Celular :" %>
                       <%= u.text_field :celular ,:disabled => true %>
                      </li>
                      <li>
                        <%= u.label :fraccionamiento, "Fraccionamiento :" %>
                        <%= u.select(:fraccionamiento) do %>
                            <% @fraccionamientos.each do |fr| %>
                                <% if @u_sent.fraccionamiento.present? && fr.id == @u_sent.fraccionamiento then %>
                                  <%= content_tag(:option, fr.nombre, value: fr.id ,:disabled => true , selected: fr.id) %>
                                <% else %>
                                  <%= content_tag(:option, fr.nombre, value: fr.id ,:disabled => true ) %>
                                <% end %>

                            <% end %>
                        <% end %>
                      </li>
                      <li>
                        <%= u.label :domicilio, "Domicilio :" %>
                        <%= u.text_field :domicilio ,:disabled => true %>
                      </li>
                      <li>
                        <%= u.label :calle, "Calle :" %>
                        <%= u.text_field :calle ,:disabled => true %>
                      </li>
                      <li>
                        <%= u.label :numero, "Numero :" %>
                        <%= u.text_field :numero ,:disabled => true %>
                      </li>
                    </ul>
                <% end %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/sentinela_usuarios/_form.html.erb
<%= render 'layouts/header_normal' %>

<div class="row"></div>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <div class="content-wrapper" style="min-height: 100%">

        <section class="content">
          <div class="table table-bordered menu-principal">
            <div class="content-div">
              <div class="row">
                <div class="col-md-11">
                  <div class="box box-primary">
                    <div class="box-header with-border">
                      <h3 class="box-title"><%= action_name %> USUARIO</h3>
                    </div>
                    <div>
                      <%= form_for(@u_sent) do |u|  %>
                          <div class="box-body">
                          <!-- <li>
                             <%= u.label :usuario, "Usuario :" %>
                             <%= u.text_field :usuario %>
                           </li>
                           -->
                           <div class="form-group">
                             <%= u.label :nombre, "Nombre :" , class:'col-sm-6' %>
                             <div class="col-sm-6">
                              <%= u.text_field :nombre , class:'form-control', :required => true%>
                             </div>
                           </div>

                           <div class="form-group">
                             <%= u.label :apellidos, "Apellidos :", class:'col-sm-6' %>
                             <div class="col-sm-6">
                               <%= u.text_field :apellidos , class:'form-control',:required => true %>
                             </div>
                           </div>

                            <div class="form-group">
                             <%= u.label :password ,"Contraseña :", class:'col-sm-6'%>
                              <div class="col-sm-6">
                                <%= u.text_field :password , class:'form-control',:required => true %>
                              </div>
                            </div>

                            <div class="form-group">
                              <%= u.label :email, "Correo Electrónico :", class:'col-sm-6' %>
                              <div class="col-sm-6">
                                <%= u.text_field :email , class:'form-control', :required => true %>
                              </div>
                            </div>

                            <div class="form-group">
                              <%= u.label :celular, "Celular :" , class:'col-sm-6'%>
                              <div class="col-sm-6">
                                <%= u.text_field :celular , class:'form-control', :required => true %>
                              </div>
                            </div>

                            <div class="form-group">
                              <%= u.label :fraccionamiento, "Fraccionamiento :" ,class:'col-sm-6' %>
                              <div class="col-sm-6">
                                <%= u.select(:fraccionamiento,options_for_select([]),{}, {class:'form-control'}) do %>
                                    <% @fraccionamientos.each do |fr| %>
                                        <% if @u_sent.fraccionamiento.present? && fr.id == @u_sent.fraccionamiento then %>
                                            <%= content_tag(:option, fr.nombre, value: fr.id , selected: fr.id) %>
                                        <% else %>
                                            <%= content_tag(:option, fr.nombre, value: fr.id ) %>
                                        <% end %>

                                    <% end %>
                                <% end %>
                              </div>
                            </div>
                           <!-- <li>
                              <%= u.label :domicilio, "Domicilio :" , class:'col-sm-6'%>
                              <%= u.text_field :domicilio , class:'form-control' %>
                            </li>-->
                            <div class="form-group">
                              <%= u.label :calle, "Calle :" , class:'col-sm-6'%>
                              <div class="col-sm-6">
                                <%= u.text_field :calle , class:'form-control', :required => true %>
                              </div>
                            </div>

                            <div class="form-group">
                              <%= u.label :numero, "Numero :" , class:'col-sm-6'%>
                              <div class="col-sm-6">
                                <%= u.text_field :numero , class:'form-control' %>
                              </div>
                            </div>

                            <div class="form-group">
                              <div class="submit-btn-form">
                                <%= u.submit  button_txt, :class => "button" %>
                              </div>
                            </div>

                          </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/sentinela_usuarios/edit.html.erb
<%= render 'form', action_name: "EDITAR",button_txt: "ACTUALIZAR INFORMACIÓN" %>

app/views/sentinela_usuarios/index.html.erb
<%= render 'layouts/header_normal' %>
<div class="row"></div>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <div class="content-wrapper" style="min-height: 100%">
        <section class="content">
          <div class="table table-bordered menu-principal">
            <div class="content-div">
              <div class="row">
                <div class="col-md-12">
                  <div class="box">
                    <div class="box-header with-border">
                      <h3 class="box-title">USUARIOS</h3>
                      <div class="box-tools">
                        <%= form_tag sentinela_usuarios_path, :method => 'get' do %>
                            <div class="input-group input-group-sm" style="width: 200px;">
                              <%= text_field_tag :buscador , params[:buscador], class:' form-control pull-right ', placeholder: 'Buscar' %>
                              <div class="input-group-btn">
                                <button type="submit" class="btn btn-default">
                                  <i class="fa fa-search"></i>
                                </button>
                              </div>
                            </div>
                        <% end %>
                      </div>
                      <div style="margin-top:-26px">
                        <%= link_to image_tag('iconos/add_white_24dp.png') + "AÑADIR USUARIO", new_sentinela_usuario_path, class: "button-link-form pull-left" %>
                      </div>
                    </div>

                  <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                      <th>#</th>
                      <th>NOMBRE</th>
                      <th>APELLIDOS</th>
                      <th>CORREO</th>
                      <th>CELULAR</th>
                      <th>PASSWORD</th>
                      <th>ACCIONES</th>
                      <% @u_sent.each_with_index do |usuario, index|%>
                          <% indexplus = index + 1 %>
                          <tr>
                            <td class="dct-td-center"><%= indexplus %></td>
                            <td><%= usuario.nombre %></td>
                            <td><%= usuario.apellidos %></td>
                            <td><%= usuario.email %></td>
                            <td><%= usuario.celular %></td>

                            <td><%= usuario.password %></td>
                            <td class="dct-td-center">
                              <%= link_to image_tag('iconos/view_black_24dp.png') , usuario %>
                              <%= link_to image_tag('iconos/edit_black_24dp.png') , edit_sentinela_usuario_path(usuario) %>
                              <%= link_to image_tag('iconos/delete_black_24dp.png') , usuario, method: :delete, data:{confirm: @mensajeborrar + usuario.nombre + "?"} %>
                            </td>
                          </tr>
                      <% end %>
                    </table>
                  </div>
                  <div class="box-footer clearfix">
                    <%= will_paginate @u_sent %>
                  </div>
                </div>
                  <div class="col-md-10">
                    <%= will_paginate @u_sent %>
                  </div>
              </div>
              </div>

            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/sentinela_usuarios/new.html.erb
<%= render 'form' , action_name:  "NUEVO", button_txt: "GUARDAR"%>

app/views/sentinela_usuarios/show.html.erb
<%= render 'form-show', action_name: "MOSTRAR", button_txt: "ACTUALIZAR INFORMACIÓN"%>