config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers =>{:registrations => 'accesos'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :admin
	resources :bitacoras do
    get 'listar', :on => :collection
  end
	resources :tutoriales
  resources :casas
	resources :calles
	resources :numeros_casas
	resources :sentinela_usuarios
	resources :visitas_registro
	resources :fraccionamientos
  root :to => 'welcome#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calle.rb
class Calle < ApplicationRecord
end

app/models/casa.rb
class Casa < ApplicationRecord
end

app/models/fraccionamiento.rb
class Fraccionamiento < ApplicationRecord

end

##@fracc = Fraccionamiento.where("nombre LIKE ?", "%#{params[:buscador]}%")

app/models/numeros_casa.rb
class NumerosCasa < ApplicationRecord
end

app/models/sentinela_usuario.rb
class SentinelaUsuario < ApplicationRecord
end

app/models/user.rb
#class User < ApplicationRecord
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(conditions={})
    find_by(celular: conditions[:email]) || find_by(email: conditions[:email])
  end
end

class User < ActiveRecord::Base
  # you can also explicitly define enum as:  enum access_level: [:employee => 0, :company_admin => 1, :super_admin => 2}
  enum rol: [:residente, :vigilante, :admin, :super_admin]

end

app/models/visitas_registro.rb
class VisitasRegistro < ApplicationRecord
end

app/controllers/accesos_controller.rb
class AccesosController < Devise::RegistrationsController

  def create
    build_resource(registration_params)

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        respond_with resource, :location => after_sign_up_path_for(resource)
      end
    else
      clean_up_passwords
      respond_with resource
    end
  end

  private

  def registration_params
    params.require(:user).permit(:email, :nombre, :apellidos, :celular,
                                 :usuario, :password)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
	def index
		@fracc = Fraccionamiento.all #variable para pedir listado de fraccionamientos
	end
	def show
		@user = User.find(params[:id])
	end
end

app/controllers/calles_controller.rb
class CallesController < ApplicationController
  def index
  end
end

app/controllers/casas_controller.rb
class CasasController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def create
  end

  def new
  end
end

app/controllers/fraccionamientos_controller.rb
class FraccionamientosController < ApplicationController
	before_action :authenticate_user!
	def index
		if params[:buscador]
			@fracc = Fraccionamiento.where("nombre LIKE ? OR clave like ? ", "%#{params[:buscador]}%" ,"%#{params[:buscador]}%").paginate(:per_page => 5, :page => params[:page])
		else
			@fracc = Fraccionamiento.all.paginate(:per_page => 5, :page => params[:page])
		end
		params[:buscador] = nil
		@mensajeborrar = "Está seguro de querer eliminar el registro "
	end
	
	def show
		@fracc = Fraccionamiento.find(params[:id])
	end

	def create
		@fracc = Fraccionamiento.new(fracc_params)
		if @fracc.save
			redirect_to @fracc
		else
			render :new
		end
	end

	def new
		@fracc = Fraccionamiento.new
	end

	def update
		@fracc = Fraccionamiento.find(params[:id])
		if @fracc.update(fracc_params)
			redirect_to action: "index"
		else
			render :edit
		end
	end
	def edit
		@fracc = Fraccionamiento.find(params[:id])
	end

	###720449222209

	def fracc_params
		params.require(:fraccionamiento).permit(:clave,:nombre,:numero_casas,:estado)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_user!
	def index
		
	end

	def admin

	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitacoras_helper.rb
module BitacorasHelper
end

app/helpers/calles_helper.rb
module CallesHelper
end

app/helpers/casas_helper.rb
module CasasHelper
end

app/helpers/fraccionamientos_helper.rb
module FraccionamientosHelper
end

app/helpers/numeros_casas_helper.rb
module NumerosCasasHelper
end

app/helpers/tutoriales_helper.rb
module TutorialesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fraccionamientos/_form.html.erb
<%= render 'layouts/header_normal' %>

<div class="row"></div>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <div class="content-wrapper" style="min-height: 100%">

        <section class="content">
          <div class="table table-bordered menu-principal">
            <div class="content-div">
              <h2><%= action_name %> FRACCIONAMIENTO</h2>

              <div>
                <%= form_for(@fracc) do |f| %>
                    <ul class="flex-form">
                      <li>
                        <%= f.label :clave, "Clave" %>
                        <%= f.text_field :clave %>
                      </li>
                      <li>
                        <%= f.label :nombre, "Nombre" %>
                        <%= f.text_field :nombre %>
                      </li>
                      <li>
                        <%= f.label :numero_casas, "Numero de Casas" %>
                        <%= f.text_field :numero_casas %>
                      </li>
                      <li>
                        <%= f.label :estado ,"estado"%>
                        <%= f.check_box :estado %>
                      </li>
                      <li>
                        <div class="submit-btn-form">
                          <%= f.submit  button_txt, :class => "button button-blue" %>
                        </div>
                      </li>
                    </ul>
                <% end %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/fraccionamientos/edit.html.erb
<%= render 'form' , action_name: "EDITAR", button_txt: "ACTUALIZAR INFORMACIÓN" %>

app/views/fraccionamientos/index.html.erb
<%= render 'layouts/header_normal' %>
<div class="row"></div>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <div class="content-wrapper" style="min-height: 100%">

        <section class="content">
          <div class="table table-bordered menu-principal">
            <div class="content-div">
              <h2>FRACCIONAMIENTOS</h2>
              <%= form_tag fraccionamientos_path, :method => 'get' do %>
                <div class="search-box">
                  <div>
                    <%= label_tag :buscador, "Buscar Fraccionamiento" %>
                    <%= text_field_tag :buscador , params[:buscador] %>
                    <%= image_submit_tag('iconos/buscar_black_24dp.png', :class=>"search-icon") %>
                  </div>
                  <div>
                    <%= link_to image_tag('iconos/add_white_24dp.png') +"AÑADIR FRACCIONAMIENTO" ,new_fraccionamiento_path, :class =>"button-link-form" %>
                  </div>
              </div>
              <% end %>
              <div class="div-container-table">
                <table>
                  <th>CLAVE</th>
                  <th>NOMBRE</th>
                  <th>ESTADO</th>
                  <th>ACCIONES</th>
                  <% @fracc.each do |fracc|%>
                  <tr>
                    <td class="dct-td-center"><%= fracc.clave %></td>
                    <td><%= fracc.nombre %></td>
                    <% if fracc.estado == 1 %>
                        <td class="td-activo">ACTIVA</td>
                    <% else %>
                        <td class="td-inactivo">INACTIVA</td>
                    <% end %>
                    <td class="dct-td-center">
                      <%= link_to image_tag('iconos/view_black_24dp.png') , fracc %>
                      <%= link_to image_tag('iconos/edit_black_24dp.png') , edit_fraccionamiento_path(fracc) %>
                      <%= link_to image_tag('iconos/delete_black_24dp.png') , fracc, method: :delete, data:{confirm: @mensajeborrar + fracc.nombre + "?"} %>
                    </td>

                  </tr>

                  <% end %>
                </table>
                <%= will_paginate @fracc %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/fraccionamientos/new.html.erb
<%= render 'form', action_name: "CREAR", button_txt: "GUARDAR" %>

app/views/fraccionamientos/show.html.erb
<%= render 'layouts/header_admin' %> 

<div class="container">
	<div><%= @fracc.clave%></div>
	<div><%= @fracc.nombre%></div>
	<div><%= @fracc.numero_casas%></div>
	<div><%= @fracc.estado%></div>

  <%= link_to "Crear" ,new_fraccionamiento_path %>
</div>